### ISSUE TITLE
Failed validating stash account address

### ISSUE THREAD

**Issue by fkbenjamin** [SimplyVC/panic_polkadot#11]
Trying to setup and test PANIC with Kusama & Polkadot, I keep getting the following error (no matter if I add Kusama or Polkadot nodes)

```
Jun 16 11:49:40 pipenv[25282]: Alert types enabled = 50
Jun 16 11:49:40 pipenv[25282]: Alert types disabled = 0
Jun 16 11:49:40 pipenv[25282]: Trying to retrieve data from the API of <node>
Jun 16 11:49:40 pipenv[25282]: Success.
Jun 16 11:49:50 pipenv[25282]: Failed validating stash account address <stash_address>
Jun 16 11:49:50 systemd[1]: panic_alerter.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 11:49:50 systemd[1]: panic_alerter.service: Failed with result 'exit-code'.
```

Looking through old issues, I found that issue #8 had the same problem and I think that upgrading the dependency of polkadot-js/api would probably solve the issue again? Since the service is failing because of that error right now, PANIC is stuck in a restart loop. Running on tag v2.0.1 right now.

**Comment by fkbenjamin** [comment]
Nevermind, I was able to solve this by editing the `package.json` of the `polkadot_api_server` to include the newest release of `@polkadot/api` and `@polkadot/api-derive` to the newest release.

**Comment by dillu24** [comment]
Thanks for opening an issue. We will issue a new API server release soon.
