### ISSUE TITLE
Vultr

### ISSUE THREAD

**Issue by TomaszWaszczyk** [SimplyVC/panic_polkadot#18]
Does it work with Vultr?

**Comment by dillu24** [comment]
Hi @TomaszWaszczyk , thanks for your question. 

Generally PANIC works if the following are satisfied:

- The nodes are updated to the latest version of Substrate.
- The chain is supported by the Polkadot JS API.
- The nodes are configured in such a way that the Polkadot API Server can connect to them.

**Comment by TomaszWaszczyk** [comment]
Hmmm so I conclude that with KSM works smoothly, right?

Thanks for your answer.

**Comment by dillu24** [comment]
Yeah it does. 

No problem, if you have any other questions let us know.
