### ISSUE TITLE
Nodes are Up but not synced

### ISSUE THREAD

**Issue by tomjohnburton** [SimplyVC/panic_polkadot#37]
Any ideas on what might be the reason?
![image](https://user-images.githubusercontent.com/39559415/123152297-ba290280-d464-11eb-9408-3c1b87a9f6f9.png)

**Comment by dillu24** [comment]
Hi @tomjohnburton thanks for opening up an issue. I think that the reason is that the UI is not able to fetch data from Redis, can you do `docker-compose logs ui` in your terminal and give me a screenshot of the logs?

**Comment by tomjohnburton** [comment]
These were the logs. FYI I'm deploying this in a k8s cluster :)

`ui`
```
Set alerter ID to polkadot-alerter
Set Polkadot API endpoint to http://polkadot-api-server
Set Mongo info to {"enabled":"true","host":"polkadot-panic-mongodb","port":"27017","db_name":"panic","user":"","pass":""}
Set Redis info to {"enabled":"true","host":"polkadot-panic-redis-headless","port":"6379","password":""}
Set chain nodes map to { 'Chainflip local Testnet': [Object] }
Set repo list to [ 'Polkadot' ]
Set Redis DB to 10
Listening on 9000```

`alerter`
```
Loading .env environment variables...
Enabled alerting channels (general): ConsoleChannel, LogChannel, MongoChannel
Enabled alerting channels (periodic alive reminder): ConsoleChannel, LogChannel, MongoChannel
Alert types enabled = 54
Alert types disabled = 0
Periodic alive reminder started.```

`api-server`
```
Connecting to ws://rpc-develop.develop:9944
2021-07-06 08:12:47        REGISTRY: Unable to resolve type AggKeySignature, it will fail on construction
2021-07-06 08:12:47        API/INIT: RPC methods not decorated: cf_p2p_subscribeNotifications, cf_p2p_unsubscribeNotifications, p2p_broadcast, p2p_send
2021-07-06 08:12:47        METADATA: Unknown types found, no types for AggKeySignature
Successfully Connected to ws://rpc-develop.develop:9944
```

**Comment by dillu24** [comment]
@tomjohnburton Can you please check if the issue it solved? It could be that panic was not getting data from the API server due to old polkadot libraries.
