### ISSUE TITLE
Use of Deprecated Polkadot API Server Functions

### ISSUE THREAD

**Issue by dillu24** [SimplyVC/panic_polkadot#6]
With the latest [polkadot-js/api](https://github.com/polkadot-js/api) update, some functions such as the `staking.currentElected` have been deprecated. This causes PANIC to crash when getting data using these functions.

**Comment by migueldingli1997** [comment]
A workaround for this problem, until it is solved, is to set any validator as a non-validator, also clearing any validator-related fields such as the stash address field from the nodes user config.
